// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnY4bkZMeAd8wFPeMdIgT0OkWdCMQJ9CQ',
    appId: '1:699936171275:web:59c0366be45d45b9922e0e',
    messagingSenderId: '699936171275',
    projectId: 'bloghub2-d4a98',
    authDomain: 'bloghub2-d4a98.firebaseapp.com',
    storageBucket: 'bloghub2-d4a98.appspot.com',
    measurementId: 'G-ZMDN7ENG68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4fVVCABTK9RiosVVzHX9b1tURx5bxJ78',
    appId: '1:699936171275:android:d252eba79bb99741922e0e',
    messagingSenderId: '699936171275',
    projectId: 'bloghub2-d4a98',
    storageBucket: 'bloghub2-d4a98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApMAEz66DJsv_XzbsyHATqwCJPVHk-EbU',
    appId: '1:699936171275:ios:0de7abdfa1954689922e0e',
    messagingSenderId: '699936171275',
    projectId: 'bloghub2-d4a98',
    storageBucket: 'bloghub2-d4a98.appspot.com',
    iosClientId: '699936171275-kkif206c91snrbelubk6gn0h6juo1pls.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloghub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApMAEz66DJsv_XzbsyHATqwCJPVHk-EbU',
    appId: '1:699936171275:ios:0de7abdfa1954689922e0e',
    messagingSenderId: '699936171275',
    projectId: 'bloghub2-d4a98',
    storageBucket: 'bloghub2-d4a98.appspot.com',
    iosClientId: '699936171275-kkif206c91snrbelubk6gn0h6juo1pls.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloghub',
  );
}
