// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8MKPmCF-C76XbTOfbx_Jsnh3DeR1brE4',
    appId: '1:230194125277:web:a9a28e90a25477ee2fbe34',
    messagingSenderId: '230194125277',
    projectId: 'proj-86865',
    authDomain: 'proj-86865.firebaseapp.com',
    databaseURL: 'https://proj-86865-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'proj-86865.appspot.com',
    measurementId: 'G-SR2WQMDERZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3qPK7NlN1wA7PICxbDm6Gm9QQHplLiEU',
    appId: '1:230194125277:android:0737f990f4fbae852fbe34',
    messagingSenderId: '230194125277',
    projectId: 'proj-86865',
    databaseURL: 'https://proj-86865-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'proj-86865.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEgLG-Zvrq7RsNyMwRvysmMGWMavbNYw4',
    appId: '1:230194125277:ios:05f8286ee3982de42fbe34',
    messagingSenderId: '230194125277',
    projectId: 'proj-86865',
    databaseURL: 'https://proj-86865-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'proj-86865.appspot.com',
    iosClientId: '230194125277-chamksjh8h2igch0170s13kc3m31qh3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEgLG-Zvrq7RsNyMwRvysmMGWMavbNYw4',
    appId: '1:230194125277:ios:05f8286ee3982de42fbe34',
    messagingSenderId: '230194125277',
    projectId: 'proj-86865',
    databaseURL: 'https://proj-86865-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'proj-86865.appspot.com',
    iosClientId: '230194125277-chamksjh8h2igch0170s13kc3m31qh3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj',
  );
}
